esphome:
  name: ${device_name}
  friendly_name: ${device_name}

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Wi‑Fi info
text_sensor:
  - platform: wifi_info
    ip_address:   { name: "${device_name} IP" }
    ssid:         { name: "${device_name} SSID" }
    bssid:        { name: "${device_name} BSSID" }
    mac_address:  { name: "${device_name} MAC" }

captive_portal:
