# D1 mini pin assignments — requires external 4.7k pull-ups on encoder pins (GPIO0/GPIO2).
substitutions:
  # Matrix rows (outputs)
  ROW1_PIN: D0    # GPIO16
  ROW2_PIN: D5    # GPIO14
  ROW3_PIN: D6    # GPIO12

  # Matrix columns (inputs with pull-up)
  COL1_PIN: D7    # GPIO13
  COL2_PIN: D1    # GPIO5
  COL3_PIN: D2    # GPIO4
  COL3_MODE: INPUT_PULLUP

  # Encoder (inputs; add 4.7k to 3V3 on both to keep HIGH at boot)
  ENC_A_PIN: D4   # GPIO2 (strap)
  ENC_B_PIN: D3   # GPIO0 (strap)
